paths:
  rgb: ./data/RGB_images/*.png #<PATHTODATA>
  nrg: ./data/NRG_images/*.png #<PATHTODATA>
  masks: ./data/masks/*.png #<PATHTODATA>
  output: ./data/generated_masks/ #<PATHTOOUTPUT>

thresholds:
  hue_min: 0.75
  hue_max: 0.95
  sat_thr: 0.25
  val_thr: 0.55

general:
  num_images: 10
  num_compare: 10

